./" man page for encode
./" Aaron (Shang Wei) Young, Katherine Chan - Fall 2014

.TH encode.1 "1 December 2014" "CSCI 241" "Oberlin College"

.SH NAME
.B encode
\- takes in file and encodes text using huffman encoding.


.SH SYNOPSIS
.B encode
[FILE1] [FILE2]

.SH DESCRIPTION
Takes in an existing FILE1, and encodes the text using huffman encoding. Encoded text will print to FILE2, and stdout if not specified. If FILE2 already exists, it will overwrite existing file. If FILE2 does not exist, it will be created automatically.

.SH AUTHOR
Aaron (Shang Wei) Young, Katherine Chan (Fall 2014)

.SH BUGS
No known bugs. 
